repos:
-   repo: local
    hooks:
    -   id: spotless-precommit
        name: Spotless Check and Apply
        description: Format code to Google Java format
        entry: bash spotless-precommit.sh
        language: system
        verbose: true